### ISSUE TITLE
Componentes proyectos 

### ISSUE THREAD

**Issue by leonelgoncalves** [Programa-TrainIT-Ar/plataforma-fe#73]

**Comment by cperezelizalde05** [comment]
Llame al end point de proyectos.

**Comment by matiasugarriza** [comment]
@leonelgoncalves  Te copio el error que me da en consola al llamar al endpoint de proyectos. Cuando puedas, por favor, coordinemos una reunión.

Access to fetch at 'http://localhost:8000/api/proyecto/proyectos/?Authorization=Bearer' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
mockServiceWorker.js:193 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at passthrough (mockServiceWorker.js:193:12)
    at getResponse (mockServiceWorker.js:241:14)
    at async handleRequest (mockServiceWorker.js:120:20)
passthrough @ mockServiceWorker.js:193
getResponse @ mockServiceWorker.js:241
ProjectService.tsx:6 
        
        
       GET http://localhost:8000/api/proyecto/proyectos/?Authorization=Bearer net::ERR_FAILED
dispatchXhrRequest @ xhr.js:209
xhr @ xhr.js:29
dispatchRequest @ dispatchRequest.js:61
_request @ Axios.js:185
request @ Axios.js:52
Axios.<computed> @ Axios.js:211
wrap @ bind.js:9
getProjects @ ProjectService.tsx:6
Projects @ page.tsx:30
renderWithHooksAgain @ react-dom-client.development.js:13463
renderWithHooks @ react-dom-client.development.js:13326
updateFunctionComponent @ react-dom-client.development.js:17933
beginWork @ react-dom-client.development.js:19839
performUnitOfWork @ react-dom-client.development.js:28368
workLoopSync @ react-dom-client.development.js:28077
renderRootSync @ react-dom-client.development.js:28032
performConcurrentWorkOnRoot @ react-dom-client.development.js:27139
workLoop @ scheduler.development.js:249
flushWork @ scheduler.development.js:218
performWorkUntilDeadline @ scheduler.development.js:525
Show 18 more frames
Show less
Axios.js:73 Uncaught (in promise) AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
handleError @ xhr.js:124
await in handleError
Axios.<computed> @ Axios.js:211
wrap @ bind.js:9
getProjects @ ProjectService.tsx:6
Projects @ page.tsx:30
renderWithHooksAgain @ react-dom-client.development.js:13463
renderWithHooks @ react-dom-client.development.js:13326
updateFunctionComponent @ react-dom-client.development.js:17933
beginWork @ react-dom-client.development.js:19839
performUnitOfWork @ react-dom-client.development.js:28368
workLoopSync @ react-dom-client.development.js:28077
renderRootSync @ react-dom-client.development.js:28032
performConcurrentWorkOnRoot @ react-dom-client.development.js:27139
workLoop @ scheduler.development.js:249
flushWork @ scheduler.development.js:218
performWorkUntilDeadline @ scheduler.development.js:525
Show 14 more frames
Show less
Access to fetch at 'http://localhost:8000/api/proyecto/proyectos/?Authorization=Bearer' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
mockServiceWorker.js:193 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at passthrough (mockServiceWorker.js:193:12)
    at getResponse (mockServiceWorker.js:241:14)
    at async handleRequest (mockServiceWorker.js:120:20)
passthrough @ mockServiceWorker.js:193
getResponse @ mockServiceWorker.js:241
ProjectService.tsx:6 
        
        
       GET http://localhost:8000/api/proyecto/proyectos/?Authorization=Bearer net::ERR_FAILED
dispatchXhrRequest @ xhr.js:209
xhr @ xhr.js:29
dispatchRequest @ dispatchRequest.js:61
_request @ Axios.js:185
request @ Axios.js:52
Axios.<computed> @ Axios.js:211
wrap @ bind.js:9
getProjects @ ProjectService.tsx:6
Projects @ page.tsx:30
renderWithHooks @ react-dom-client.development.js:13312
updateFunctionComponent @ react-dom-client.development.js:17933
beginWork @ react-dom-client.development.js:19839
performUnitOfWork @ react-dom-client.development.js:28368
workLoopSync @ react-dom-client.development.js:28077
renderRootSync @ react-dom-client.development.js:28032
performConcurrentWorkOnRoot @ react-dom-client.development.js:27139
workLoop @ scheduler.development.js:249
flushWork @ scheduler.development.js:218
performWorkUntilDeadline @ scheduler.development.js:525
Show 17 more frames
Show less
Axios.js:73 Uncaught (in promise) AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

**Comment by matiasugarriza** [comment]
@leonelgoncalves Te adjunto captura del mismo error.

![Image](https://github.com/user-attachments/assets/4a345af3-71fe-4b9d-8b7b-58938e5d12ec)
